# Generated by Django 4.2 on 2023-05-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='test.jpg', null=True, upload_to=''),
        ),
    ]
